### ISSUE TITLE
error in libdvbpsi 

### ISSUE THREAD

**Issue by cybernard** [mkrufky/libdvbtee#14]
This is a recording from a hdhomerun using a file recorded from OTA
Mythtv dvr recorded file.

dvbtee  -F 1101_20160207045500.ts  -O7 -ofile://output.ts
# dvbtee v0.4.3 - http://github.com/mkrufky/libdvbtee

_open_file: using 1101_20160207045500.ts
store PAT: v0, ts_id: 3223
           1 | 30
store PMT: v18, service_id 1, pcr_pid 49
  es_pid | type
      31 | 0x02 (Video MPEG-2) |
      34 | 0x81 (Audio AC3 (ATSC)) | eng
      35 | 0x81 (Audio AC3 (ATSC)) | spa
      36 | 0x81 (Audio AC3 (ATSC)) | eng
Error: libdvbpsi error (PSI decoder): TS discontinuity (received 2, expected 1) for PID 0
-d1 get this addition info

1454911323 [PMT]::store: { "pcrPid": 49, "program": 1, "streams": [ { "pid": 49, "streamType": 2, "streamTypeString": "Video MPEG-2" }, { "descriptors": [ { "bitRateCode": 18, "bsid": 8, "bsmod": 0, "description": "", "descriptorTag": 129, "fullSvc": true, "numChannels": "2/0", "sampleRate": "48", "surroundMode": "Not indicated" }, { "ISO639Lang": [ { "audioType": 0, "language": "eng" } ], "descriptorTag": 10 } ], "pid": 52, "streamType": 129, "streamTypeString": "Audio AC3 (ATSC)" }, { "descriptors": [ { "bitRateCode": 6, "bsid": 8, "bsmod": 5, "description": "", "descriptorTag": 129, "fullSvc": true, "numChannels": "1/0", "sampleRate": "48", "surroundMode": "Not indicated" }, { "ISO639Lang": [ { "audioType": 0, "language": "spa" } ], "descriptorTag": 10 } ], "pid": 53, "streamType": 129, "streamTypeString": "Audio AC3 (ATSC)" }, { "descriptors": [ { "bitRateCode": 6, "bsid": 8, "bsmod": 2, "description": "", "descriptorTag": 129, "fullSvc": true, "numChannels": "1/0", "sampleRate": "48", "surroundMode": "Not indicated" }, { "ISO639Lang": [ { "audioType": 0, "language": "eng" } ], "descriptorTag": 10 } ], "pid": 54, "streamType": 129, "streamTypeString": "Audio AC3 (ATSC)" } ], "tableId": 2, "tableName": "PMT", "version": 18 }

-d3 reveals this additional info
1454911567 decode::updateTable: 0x02
1454911567 parse::take_pmt: (post): v18, service_id 1, pcr_pid 49
1454911567 parse::process_pmt: : v18, service_id 1, pcr_pid 49
Error: libdvbpsi error (PSI decoder): TS discontinuity (received 2, expected 1) for PID 0
1454911567 parse::take_pat: (pre): v0, ts_id: 3223
1454911567 parse::set_ts_id: (0c97|3223)

**Comment by mkrufky** [comment]
> Error: libdvbpsi error (PSI decoder): TS discontinuity (received 2, expected 1) for PID 0

There is a minor glitch in your recorded stream -- this is not a software error.

Each PID has a packet counter.  This can be used to aid in detection of whether the receiver has missed any data, so that it can reset decoders, etc as necessary.

The `TS discontinuity error for PID 0` just means that the packet counter check for `PID 0` has failed.  This indicates to us that some data flow is temporarily interrupted in the stream.  All the data that we need is there and already decoded, but since this is broadcast television, this data is usually broadcast over and over again.  In your recording there is at least a single packet missing in this data stream, so it shows up to `libdvbpsi` as a continuity error.

Continuity errors are completely normal for recorded transport streams. I think this particular message in `libdvbpsi` should be changed to a warning rather than an error, but it's not relevant to `libdvbtee`.


Now, just some extra information, if you're curious as to exactly what kind of data it is in this `PID 0`:

`PID 0` is where transport stream parsers look for the **PAT** (_Program Association Table_).  The **PAT** is basically an index of the programs within the stream.

There is often more than one program in a broadcast transport stream. The packets for these programs are **muxed** together into a single transport stream and are parsed & filtered on the receiving end.  The **PAT** is used to communicate which packets are relevant to each program being broadcast in the current mux.


I repeat, `dvbtee` is behaving correctly here - this is not an error or bug.

**Comment by mkrufky** [comment]
Any other questions, @cybernard ?

**Comment by grkblood13** [comment]
Is there a way to omit this "warning"? I'm trying to capture epg data to build an xmltv file using ` ./dvbtee/dvbtee -c$CHANNUM -e` and these errors that occur constantly are making it impossible.

**Comment by mkrufky** [comment]
@grkblood13 you'll have to be more specific
