### ISSUE TITLE
Quoting issue in JSON output

### ISSUE THREAD

**Issue by MarkusJg** [mkrufky/libdvbtee#15]
I want to use dvbtee JSON output to extract EPG information from my stored ts-files.
It looks that I found an issue here:
When a description already contains text quoted with double quotes, the JSON output gets invalid, because this description is wrapped again with double quotes without escaping the inner quotes, see below (...""Mein ...)
`{ "descriptors": [ { "descriptorTag": 77, "lang": "deu", "name": ""Mein Kampf". Das gefährliche Buch", "text": "Dokumentation Deutschland 2014" } ]`
I'm not a C++ programmer, so it would be difficult to help myself here. Would be great if anybody could fix this. Thanks!

**Comment by mkrufky** [comment]
This issue is actually caused by the `valobj` component of within `libdvbtee` , which I have broken out into a separate development repository some time ago.  Latest builds of `valobj` have some new features that are not necessary for `libdvbtee`, but it will also be easier to fix this issue using the latest `valobj` .  I'm currently working on updating `libdvbtee` to use the new version, then I will fix the quoting issue.

**Comment by mkrufky** [comment]
@MarkusJg , I threw a small patch together that should solve your problem while waiting for the more proper fix... Can you test the code in the [escape-quotes-dr_4d#15](https://github.com/mkrufky/libdvbtee/tree/escape-quotes-dr_4d%2315) branch?

**Comment by andrewfblake** [comment]
Hey Mkrufky! Just noticed the same thing!  (love this app btw) ... I'll happily test it for you (however i'm a windows guy and have no idea how to build this from theraw source!) If I can get a windows build i'll test away!... cheers!  P.s. how do you convert the "startTime": 965444908611  to a datetime? is it in ticks or milliseconds and/or offset by epoch or something?! Cant seem to work it out! :-) thanks! Andrew

**Comment by mkrufky** [comment]
@andrewfblake , The timestamps output by libdvbtee should already be displayed in a datetime format...  Can you show me the specific output you are refering to?  (also, this should probably be moved to a separate issue)  Either way, if you google UNIX timestamp conversion and plug in the `965444908611` value, you'll find that the value itself is wrong.  Please open a new issue with the output from libdvbtee so that I can look into this and fix that.  As for testing under windows, there is some good info in issue #12 that explains how to set up a cross build for windows using some external scripts... Thanks for the feedback!

**Comment by MarkusJg** [comment]
@mkrufky Thanks a lot for this quick-fix solution. For me it works really fine. The json output is correct now and I can further develop my own scripts based on this.
Thanks! Markus

**Comment by mkrufky** [comment]
Please note: there was a memory leak in the test patch that I provided for this feature.  I have fixed the problem and merged the feature into the master branch.  Please try again using the latest master.
